apiVersion: v1
kind: Secret
metadata:
  name: docker-test-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRtbDBiM0l4TWpNME5UWTZaR05yY2w5d1lYUmZkMVYyVEZWVFVXdGtiV2QxZGs5RFVsQjBSM2RTTlVKSGFreFYiCgkJfQoJfQp9